### ISSUE TITLE
error: ‘numeric_limits’ is not a member of ‘std’, update c++ lib required

### ISSUE THREAD

**Issue by arkanoid87** [scemino/clipper2#1]
https://github.com/AngusJohnson/Clipper2/pull/296/commits/117ef1405ed9c25cffa3aa060369f6aca4d07803

**Comment by scemino** [comment]
What is your operating system ?

**Comment by arkanoid87** [comment]
Ubuntu 22.04

By manually including <limits> just like in the linked commit it compiles correctly

Ps: i strongly suggest to copypaste the example at the botton of the wrapper nim file in the github readme
